### ISSUE TITLE
 To-do list

### ISSUE THREAD

**Issue by tshort** [tshort/CodeGen.jl#1]
Here are known things that need work:

- [x] Rename functions to support multiple dispatch
- [x] Support recursion
- [ ] Support global variables
- [ ] Support Union types
- [ ] More intrinsics
- [ ] Add a way to override `codegen!` methods, probably by adding a type parameter to `CodeCtx`
- [ ] Add a way to intercept function calls to substitute something more "native"
